docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
      - Configuration: config.md
      - "Debug Provider": debug.md
      - Templates: templates.md
site_name: 'phly'
site_description: 'league/oauth2-client adapter for zend-expressive-authentication'
repo_url: 'https://github.com/phly/phly-expressive-oauth2clientauthentication'
copyright: 'Copyright (c) 2019 <a href="https://mwop.net">Matthew Weier O&#39;Phinney</a>'
theme: windmill
